"""Generate the data/mechanics coverage reports used by docs/.

Outputs:
  docs/DATA_REPORT.md      - library contents, sources, verification status
  docs/COVERAGE.md         - per-skill mechanics coverage (modelled vs unmodelled)
  data/mechanics/coverage.json - machine readable version of the same
"""

from __future__ import annotations

import json
import os
from typing import Dict, List

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.path.join(ROOT, "data")
DOCS = os.path.join(ROOT, "docs")


def load(path: str):
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def count_one(effect: Dict) -> int:
    """Count an effect, including the sub-effects of a compound clause."""
    return 1 + sum(count_one(sub) for sub in effect.get("sub_effects", []))


def count_effects(entry: Dict) -> int:
    total = 0
    for key in (
        "on_use",
        "clash_win",
        "clash_lose",
        "attack_end",
        "combat_start",
        "before_attack",
        "on_kill",
        "on_evade",
        "turn_start",
        "turn_end",
    ):
        total += sum(count_one(e) for e in entry.get(key, []))
    for coins in entry.get("coins", {}).values():
        total += sum(count_one(e) for e in coins)
    for coins in entry.get("heads_hit", {}).values():
        total += sum(count_one(e) for e in coins)
    return total


def passive_section() -> list:
    rows = passive_rows()
    if not rows:
        return []
    lines = [
        "",
        "## Passives",
        "",
        "Identity / enemy Passives (`data/passives/passives.json`).  Modelled "
        "clauses run at Combat Start / Turn Start / Turn End / Attack End and as "
        "continuous modifiers; clauses still `unmodelled` are listed by "
        "`Simulator::passive_gaps()`.",
        "",
        "| id | owner | kind | name | modelled | unmodelled | hand-modelled in |",
        "|----|-------|------|------|----------|------------|------------------|",
    ]
    for pid, owner, kind, name, modelled, unmodelled, hand in rows:
        lines.append(
            f"| `{pid}` | `{owner}` | {kind} | {name} | {modelled} | {unmodelled} | {hand} |"
        )
    return lines


def passive_rows() -> list:
    path = os.path.join(DATA, "passives", "passives.json")
    if not os.path.exists(path):
        return []
    book = load(path)["passives"]
    rows = []
    for pid in sorted(book):
        entry = book[pid]
        effects = entry.get("effects", {})
        modelled = sum(
            len(v) for k, v in effects.items() if isinstance(v, list) and k != "unmodeled"
        )
        unmodelled = len(effects.get("unmodeled", []))
        rows.append(
            (
                pid,
                entry.get("owner", ""),
                entry.get("kind", ""),
                entry.get("name") or "",
                modelled,
                unmodelled,
                entry.get("hand_modelled") or "",
            )
        )
    return rows


def main() -> int:
    os.makedirs(DOCS, exist_ok=True)
    effects = load(os.path.join(DATA, "mechanics", "effects.json"))["skills"]
    identities = {}
    for name in sorted(os.listdir(os.path.join(DATA, "identities"))):
        rec = load(os.path.join(DATA, "identities", name))
        identities[rec["id"]] = rec
    egos = {}
    for name in sorted(os.listdir(os.path.join(DATA, "ego"))):
        rec = load(os.path.join(DATA, "ego", name))
        egos[rec["id"]] = rec
    enemies = {}
    for name in sorted(os.listdir(os.path.join(DATA, "enemies"))):
        rec = load(os.path.join(DATA, "enemies", name))
        enemies[rec["id"]] = rec
    statuses = load(os.path.join(DATA, "statuses", "statuses.json"))

    coverage: Dict[str, dict] = {}
    lines: List[str] = []
    lines.append("# Mechanics coverage\n")
    lines.append(
        "Generated by `tools/report.py`.  `modelled` counts the effect clauses the "
        "extractor translated into an engine-supported kind; `unmodelled` lists the "
        "effect-text lines the engine does **not** model.  Strict mode refuses to run "
        "a skill with a non-empty `unmodelled` list.\n"
    )

    for label, records in (("Identities", identities), ("Enemies", enemies)):
        lines.append(f"\n## {label}\n")
        lines.append("| id | name | slots | modelled | unmodelled |")
        lines.append("|----|------|-------|----------|------------|")
        for rid, rec in records.items():
            slots = rec.get("skills", [])
            modelled = 0
            unmodelled = 0
            for skill in slots:
                tiers = skill.get("upties") or {"1": skill}
                for tier_key in tiers:
                    entry = effects.get(f"{skill['id']}@{tier_key}")
                    if not entry:
                        continue
                    if label == "Enemies" and tier_key != "1":
                        continue
                    modelled += count_effects(entry)
                    unmodelled += len(entry.get("unmodeled", []))
            name = rec.get("title_en") or rec.get("name_en") or ""
            lines.append(
                f"| `{rid}` | {name} | {len(slots)} | {modelled} | {unmodelled} |"
            )
            coverage[rid] = {"modelled": modelled, "unmodelled": unmodelled}

    lines.append("\n## E.G.O\n")
    lines.append("| id | name | resource cost | SP (awakening/corrosion) | modelled | unmodelled |")
    lines.append("|----|------|---------------|--------------------------|----------|------------|")
    for eid, rec in egos.items():
        modelled = 0
        unmodelled = 0
        for kind in ("awakening", "corrosion"):
            entry = effects.get(f"{eid}.{kind}@1")
            if not entry:
                continue
            modelled += count_effects(entry)
            unmodelled += len(entry.get("unmodeled", []))
        cost = ", ".join(f"{k} {v}" for k, v in rec.get("resource_cost", {}).items())
        lines.append(
            f"| `{eid}` | {rec.get('name_en')} | {cost} | "
            f"{rec.get('awakening_sp')}/{rec.get('corrosion_sp')} | {modelled} | {unmodelled} |"
        )
        coverage[eid] = {"modelled": modelled, "unmodelled": unmodelled}

    lines.extend(passive_section())
    with open(os.path.join(DOCS, "COVERAGE.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    with open(os.path.join(DATA, "mechanics", "coverage.json"), "w", encoding="utf-8") as fh:
        json.dump(coverage, fh, ensure_ascii=False, indent=1, sort_keys=True)

    # data report
    out: List[str] = ["# Data library report\n"]
    out.append(
        "Generated by `tools/report.py`.  Two independent sources are joined on the "
        "official in-game id.\n"
    )
    sources = load(os.path.join(DATA, "sources", "_index.json"))
    out.append("## Sources\n")
    out.append(
        f"- wiki.gg (en): {sources['wiki']['site']} - {len(sources['wiki']['fetched_pages'])} pages cached, "
        "access via r.jina.ai because direct requests are blocked by the host's WAF."
    )
    gamedata = sources.get("game_text", {})
    for key in ("en", "zh_cn"):
        info = gamedata.get(key, {})
        if info:
            out.append(
                f"- game text ({info.get('language')}): `{info.get('repo')}` "
                f"@ `{str(info.get('commit'))[:10]}` ({info.get('kind')})"
            )
    out.append("\n## Identities\n")
    out.append("| id | name (en) | name (zh-CN) | rarity | season | hp | speed | stagger |")
    out.append("|----|-----------|--------------|--------|--------|----|-------|---------|")
    for rid, rec in identities.items():
        stats = rec["stats"]
        out.append(
            f"| `{rid}` | {rec.get('title_en')} | {rec.get('title_zh')} | {rec.get('rarity')} | "
            f"{rec.get('season')} | {stats.get('hp')} (+{stats.get('hp_growth')}/lv) | "
            f"{stats.get('speed')} | {stats.get('stagger_thresholds')} |"
        )
    out.append("\n## Statuses modelled\n")
    out.append("| key | name (en) | name (zh-CN) | effect |")
    out.append("|-----|-----------|--------------|--------|")
    for status in statuses:
        text = (status.get("text_en") or "").replace("\n", " ").replace("|", "/")
        out.append(
            f"| `{status['key']}` | {status.get('name_en')} | {status.get('name_zh')} | {text[:160]} |"
        )
    with open(os.path.join(DOCS, "DATA_REPORT.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(out) + "\n")

    print("wrote docs/COVERAGE.md, docs/DATA_REPORT.md, data/mechanics/coverage.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
